import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryClientProvider from "@/app/Util/QueryClientProvider";
import Nav from "@/app/View/Component/Nav";
import Footer from "@/app/View/Component/Footer";
import {getCredential} from "@/app/Util/constants/session";
import {AuthProvider} from "@/app/auth/context";
import React from "react";
import {CartProvider} from "@/app/View/product/CartContext";
import CartSideBar from "@/app/View/Component/utilties/CartSideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const user = await getCredential();
    return (
    <html lang="en" data-theme="bumblebee">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <QueryClientProvider>
          <AuthProvider user={user} isPending={false}>
              <CartProvider>
                  <CartSideBar/>
                  <Nav/>
                  <main>
                      {children}
                  </main>
                  <Footer/>
              </CartProvider>
          </AuthProvider>
      </QueryClientProvider>
      </body>
    </html>
  );
}
